server:
  port: 8085
  servlet:
    context-path: /gis
    
spring:
  application:
     name: gis
  datasource:
    password: ${DB_PASSWORD:jforce}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yanginanomali}
    username: ${DB_USER:jforce}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: yas
        format_sql: false
    show-sql: true

geo-metrics:
  buffer-distance: 0.0050 # 500-560 meter

springdoc:
  api-docs:
    enabled: true
    path: /api/swagger/v3/api-docs
  swagger-ui:
    path: /api/swagger/swagger-ui.html

management:
    endpoints:
        web:
          exposure:
              include: ["prometheus"]
