server:
  port: 8085
  servlet:
    context-path: /gis
    
spring:
  application:
     name: gis
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yanginanomali}
    username: ${DB_USER:jforce}
    password: ${DB_PASSWORD:jforce}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true
        database: postgresql
        jdbc:
          lob:
          non_contextual_creation: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        default_schema: YAS
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

geo-metrics:
  buffer-distance: 0.0050 # 500-560 meter
