server:
  port: 8082
  servlet:
    context-path: /proposal
spring:
  application:
    name: proposal
  datasource:
    password: ${DB_USER:jforce}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yanginanomali}
    username: ${DB_USER:jforce}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: yas
        format_sql: false
    show-sql: true

rule-service: drools

service:
  endpoints:
    auth-server:
      internal-validate-token: http://localhost:7000/auth-server/api/internal/validate
    anomaly-detective:
      predict-service: http://localhost:8081/anomaly-detective/ai-query/proposal/predict
    odm:
      proposal-brms-score-service: http://localhost:9090/DecisionService/rest/xxxxx
    drools:
      proposal-brms-score-service: http://localhost:8084/droolspot/api/drools/run/proposal

springdoc:
  api-docs:
    enabled: true
    path: /api/swagger/v3/api-docs
  swagger-ui:
    path: /api/swagger/swagger-ui.html
